### ISSUE TITLE
I Get this error even after installing (No module named 'pyroute2.netns.nslink) after  sudo pip3 install pyroute2 Requirement already satisfied: pyroute2 in /usr/local/lib/python3.9/dist-packages (0.7.12)

### ISSUE THREAD

**Issue by noahwalugembe** [CN-TU/machine-learning-in-ebpf#4]
I Get this error even after installing (No module named 'pyroute2.netns.nslink) after  sudo pip3 install pyroute2 Requirement already satisfied: pyroute2 in /usr/local/lib/python3.9/dist-packages (0.7.12)

sudo python3 test.py --run_scenario just_one_flow
Traceback (most recent call last):
  File "/home/noah/aiebpf/test.py", line 15, in <module>
    import virtnet
  File "/usr/local/lib/python3.9/dist-packages/virtnet/__init__.py", line 9, in <module>
    from . host import Host, PhysicalHost, Router
  File "/usr/local/lib/python3.9/dist-packages/virtnet/host.py", line 16, in <module>
    from pyroute2.netns.nslink import NetNS
ModuleNotFoundError: No module named 'pyroute2.netns.nslink'

**Comment by muxamilian** [comment]
I think the problem is that py-virtnet only supports python 3.7
py-virtnet is not actively maintained at the moment, so there is no plan to add support for newer python versions unfortunately. 
However, py-virtnet is not essential to run the ebpf code. It’s just a python package to simulate a network.

**Comment by noahwalugembe** [comment]
i tried Set python version to 3.7.9{
pyenv install 3.7.9
pyenv local 3.7.9
pyenv global 3.10.11)} but it still did not work am new to ebpf how can is test the ebpf machine learning project with out running the pythn script Debian 11

**Comment by muxamilian** [comment]
Since many software packages (python, py-virtnet, mininet, etc.) changed since this work was released, unfortunately, the code in this repo only works using the exact same versions that I used (as stated in the README).  Also, the eBPF specification changed in the last years and now has more functionality.
